export const dashboardPaths = {
  login: '/admin/login',
  logout: '/admin/logout',
  overview: '/admin',
  users: '/admin/users',
  roles: '/admin/roles',
  groups: '/admin/groups',
  groupDetail: (id: string) => `/admin/groups/${id}`,
  policies: '/admin/policies',
  policyDetail: (id: string) => `/admin/policies/${id}`,
  devices: '/admin/devices',
  deviceDetail: (id: string) => `/admin/devices/${id}`,
  apps: '/admin/apps',
  appDetail: (id: string) => `/admin/apps/${id}`,
  managedFiles: '/admin/managed-files',
  managedFileDetail: (id: string) => `/admin/managed-files/${id}`,
  certificates: '/admin/certificates',
  certificateDetail: (id: string) => `/admin/certificates/${id}`,
  commands: '/admin/commands',
  logs: '/admin/logs',
  deviceInfo: '/admin/device-info',
  audit: '/admin/audit',
} as const;
